name: Python Dist

on:
  pull_request:
    paths:
      - 'bindings/python/**'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: dist-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./bindings/python
    shell:
        bash -eux {0}

jobs:
  build-dist:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: |
          python -m pip install -U pip setuptools wheel packaging
          git fetch origin --tags

      - name: Build Wheels
        run:  |
          MACOSX_DEPLOYMENT_TARGET=10.14 PYTHON=$(which python) ./release.sh

      - name: Test Wheel on Non-Ubuntu
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}
        run: |
          pip install ./dist/*.whl
          cd $HOME
          python -c "import pymongocrypt; print(pymongocrypt.libmongocrypt_version())"

      - name: Test Wheel on Ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          pip install ./dist/*manylinux_2_12*.whl
          cd $HOME
          python -c "import pymongocrypt; print(pymongocrypt.libmongocrypt_version())"

      - uses: actions/upload-artifact@v2
        with:
          name: pymongocrypt-${{ matrix.os }}-dist
          path: ./bindings/python/dist/*.*
          if-no-files-found: error

  collect-dist:
    runs-on: ubuntu-latest
    needs: [build-dist]
    name: Download Dist Files
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Flatten directory
        working-directory: .
        run: |
          find . -mindepth 2 -type f -exec mv {} . \;
          find . -type d -empty -delete
      - uses: actions/upload-artifact@v2
        with:
          name: all-dist
          path: "./*"
