name: Python Dist

on:
  push:
    paths:
      - 'bindings/python/**'
  pull_request:
    paths:
      - 'bindings/python/**'
  workflow_dispatch:

concurrency:
  group: dist-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pypa/cibuildwheel@v2.3.1
        with:
          package-dir: ./bindings/python
      - uses: actions/upload-artifact@v2
        with:
          name: pymongocrypt-${{ matrix.os }}-wheel
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  build-sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Build SDist
        working-directory: ./bindings/python
        run: |
          set -ex
          python -m pip install -U pip build
          python -m build --sdist .

  collect-dist:
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    name: Download Wheels
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Flatten directory
        run: |
          find . -mindepth 2 -type f -exec mv {} . \;
          find . -type d -empty -delete
      - uses: actions/upload-artifact@v2
        with:
          name: all-dist
          path: "./*"
