name: Python Dist

on:
  push:
    paths:
      - 'bindings/python/**'
  pull_request:
    paths:
      - 'bindings/python/**'
  workflow_dispatch:

concurrency:
  group: dist-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./bindings/python
    shell:
        bash -eux {0}

jobs:
  build-windows-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
    name: Build ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install Dependencies
        run: python -m pip install -U build pip

      - name: Handle libmongocrypt on Macos
        if: ${{ startsWith(matrix.os, 'macos' }}
        run:  LIBMONGOCRYPT_TARGET=macos bash ./bindings/python/handle_libmongocrypt.sh

      - name: Handle libmongocrypt on Windows
        if: ${{ startsWith(matrix.os, 'windows' }}
        run:  LIBMONGOCRYPT_TARGET=windows bash ./bindings/python/handle_libmongocrypt.sh

      - name: Handle libmongocrypt on Linux
        if: ${{ startsWith(matrix.os, 'linux' }}
        run:  LIBMONGOCRYPT_TARGET=linux bash ./bindings/python/handle_libmongocrypt.sh

      - name: Build SDist on Linux
        if: ${{ startsWith(matrix.os, 'linux' }}
        run:  python -m build --sdist

      - name: Build and Test Wheel
        run:
          python -m build --wheel
          pip install ./dist/*.whl
          cd $HOME
          python -c "pymongocrypt; print(pymongocrypt.libmongocrypt_version())"

      - uses: actions/upload-artifact@v2
        with:
          name: pymongocrypt-${{ matrix.os }}-dist
          path: ./bindings/python/dist/*.*
          if-no-files-found: error

  collect-dist:
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    name: Download Dist Files
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Flatten directory
        run: |
          find . -mindepth 2 -type f -exec mv {} . \;
          find . -type d -empty -delete
      - uses: actions/upload-artifact@v2
        with:
          name: all-dist
          path: "./*"
